home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "home"
urlpatterns = [
   path('', index, name="home") 
]

imti2019/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('investiga/', include('investiga.urls')),
    path('kastrat-tv/', include('kastrattv.urls')),
    path('news/', include('news.urls')),
    path('sop-kunjungan', include('sopkunjungan.urls')),
]

investiga/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
app_name  = "investiga"
urlpatterns = [
    path('', investiga, name="investiga")
]

kastrattv/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "kastrattv"
urlpatterns = [
    path('', kastrattv, name="kastrattv")
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "news"
urlpatterns = [
    path('review-article/<str:judul>', NewsView, name='news'),
    path('PO-article/<str:judul>', POView, name='po'),
    path('PO-Announcement', POEvent , name='POEvent'),
    path('Review-Event', CardEvent , name='CardEvent' ),

]

sopkunjungan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import sopkunjungan as sopview
app_name = "sopkunjungan"
urlpatterns = [
    path('', sopview, name="sopkunjungan")
]

home/models.py
from django.db import models

# Create your models here.

investiga/models.py
from django.db import models

# Create your models here.
class Investiga(models.Model):
    judul = models.CharField(max_length = 500)
    link = models.CharField(max_length=1000)

kastrattv/models.py
from django.db import models

# Create your models here.
class kastrattv(models.Model):
    link = models.CharField(max_length = 1000)
    judul = models.CharField(max_length=500)

news/models.py
from django.db import models
from datetime import datetime,date
from django.utils import timezone
# Create your models here.

class NewsEvent(models.Model):
	judul = models.CharField(max_length = 100 , primary_key = True)
	isi = models.TextField(default ='Artikel IMTI')
	foto = models.CharField(max_length = 350, default='#')

class NewsPO(models.Model):
	judul = models.CharField(max_length = 100, primary_key = True)
	isi = models.TextField(default ='Pengumuman PO')
	foto = models.CharField(max_length = 350, default='#')

sopkunjungan/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

investiga/views.py
from django.shortcuts import render
from .models import Investiga as InvestigaData
# Create your views here.
def investiga(request):
    respond = {}
    datas = InvestigaData.objects.all()
    respond['datas'] = datas
    return render(request, 'investiga/investiga.html', respond)

kastrattv/views.py
from django.shortcuts import render
from django.forms.models import model_to_dict
from .models import kastrattv as Kastrat
# Create your views here.
def kastrattv(request):
    respond = {}
    datas = Kastrat.objects.all()
    respond['datas'] = datas
    return render(request, 'kastrattv/kastrattv.html', respond)
#     for data in datas:
#         each_data = model_to_dict(data)
#         print(each_data)

# def 

news/views.py
from django.shortcuts import render
from .models import *
from django.shortcuts import get_object_or_404

# Create your views here.

def NewsView(request, judul):
	news = get_object_or_404(NewsEvent, pk=judul)
	return render(request, 'news/EventBaru.html', { 
		'judul':news.judul, 'isi':news.isi, 'foto':news.foto
		})

def POView(request, judul):
	news = get_object_or_404(NewsPO, pk=judul)
	return render(request, 'news/PObaru.html', { 
		'judul':news.judul, 'isi':news.isi, 'foto':news.foto
		})

def CardEvent(request):
	return render(request,'news/EventCard.html')

def POEvent(request):
	return render(request, 'news/POCard.html')

sopkunjungan/views.py
from django.shortcuts import render

# Create your views here.
def sopkunjungan(request):
    return render(request, 'sopkunjungan/sopkunjungan.html')

home/templates/home/index.html
{%extends 'base.html'%}
{%load static%}
{%block head%}
<link href="{%static 'css/home/home.css'%}" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
IMTI 2019
{%endblock%}
{%block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-12">
            <img src="{%static 'media/home/LOGO-IMTI-1.png'%}" class="img-fluid" alt="IMTI LOGO">
        </div>
    </div>
    <div class="text-white row dark-blue-bg mb-5 p-3">
        <div class="col-12 col-md-12">
            <div class="text-center">
                    <h2 class="mt-1">Nilai</h2>
            </div>
        </div>
        
        
    </div>
    <div class="row mb-5">
        <div class="col-12 col-md-4 text-center mb-4"><i class="fas fa-7x fa-cogs dark-blue"></i></div>
        <div class="col-12 col-md-8">
            <h3>Sinergis</h3>
            
                <div class="strip blue-strip mb-1"></div>
                <div class="strip red-strip mb-3"></div>
        
            <p>Membangun dan memastikan hubungan kerjasama yang produktif dan
                kreatif serta kemitraan yang harmonis secara internal maupun external IMTI FTUI
                2019 dengan saling mengisi dan melengkapi perbedaan untuk mencapai hasil lebih
                besar daripada Jumlah bagian per bagian.</p>
        </div>
    </div>
    <div class="row mb-5">
        <div class="mobile col-12 col-md-4 text-center mb-4"><i class="fas fa-dice-d20 fa-7x dark-blue"></i></div>
        <div class="col-12 col-md-8 text-right">
            <h3>Integrasi</h3>
            <div class="strip blue-strip mb-1 float-right"></div>
            <div class="strip red-strip mb-3 float-right"></div>
            <p>Mengintegrasikan keduabelas bidang juga subsistem yang terdapat pada
                IMTI FTUI dengan satu sama lain maupun IMTI secara keseluruhan dengan para
                pemangku kepentingannya untuk menghasilkan karya yang bermanfaat dan
                berkualitas bagi warga TI UI dan sekitarnya.</p>
        </div>
        <div class="desktop col-12 col-md-4 text-center mb-4"><i class="fas fa-dice-d20 fa-7x dark-blue"></i></div>
    </div>
    <div class="row mb-5">
        <div class="col-12 col-md-4 text-center mb-4"><i class="fas fa-paint-brush fa-7x dark-blue"></i></div>
            <div class="col-12 col-md-8">
                <h3>Berkreasi</h3>
                <div class="strip blue-strip mb-1"></div>
                <div class="strip red-strip mb-3"></div>
                <p>Mengoptimalkan pemanfaatan dari kreatifitas mahasiswa TI UI dalam
                    menginovasikan program-program pada IMTI FTUI juga membuat iklim yang
                    produktif agar mahasiswa TI UI dapat mengaktualisasikan dirinya sesuai dengan
                    minat, bakat, dan potensi pada dirinya.</p>
            </div>
        </div>
</div>
{%endblock%}

investiga/templates/investiga/investiga.html
{%extends "base.html"%}
{%load static%}
{%block title%}
Kastrat TV
{%endblock%}

{%block content%}
<div class="container">
        <h1>Investiga</h1>
        <div class="strip blue-strip mb-1"></div>
        <div class="strip red-strip mb-3"></div>

    <div class="row">
        {%for data in datas %}
        <div class="col-12 col-md-4 text-center mb-3">
            {% autoescape off %}
            {{data.link}}
            {%endautoescape%}
            <h3>{{data.judul}}</h3>
        </div>
        {%endfor%}
    </div>
    
</div>
{%endblock%}

kastrattv/templates/kastrattv/kastrattv.html
{%extends "base.html"%}
{%load static%}
{%block title%}
Kastrat TV
{%endblock%}
{%block content%}
<div class="container">
        <h1>Kastrat TV</h1>
        <div class="strip blue-strip mb-1"></div>
        <div class="strip red-strip mb-3"></div>
    <div class="row">
        
        {%for data in datas %}
        <div class="col-12 col-md-6 text-center mb-3">
            {% autoescape off %}
            {{data.link}}
            {%endautoescape%}
            <h3>{{data.judul}}</h3>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

news/templates/news/EventBaru.html
<!DOCTYPE html>
<html>
<head>
	<title>{{judul}}</title>
</head>
<body>

</body>
</html>

news/templates/news/EventCard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Review Event</title>
  </head>
  <body>


    <div class="card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Judul</h5>
    <p class="card-text">isi</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
    

  </body>
</html>

news/templates/news/POCard.html
{%extends "base.html"%}
{%load static%}
{%block title%}
PO Announcement
{%endblock%}
{%block content%}


<div class="card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Judul</h5>
    <p class="card-text">isi</p>
    <a href="#" class="btn btn-primary">Read More</a>
  </div>
</div>
    

{%endblock%}


    

  

news/templates/news/PObaru.html
<!DOCTYPE html>
<html>
<head>
	<title>{{judul}}</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon-16x16.png'%}">
    <link rel="manifest" href="{% static 'media/site.webmanifest'%}">
    <link rel="mask-icon" href="{% static 'media/safari-pinned-tab.svg'%}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- link fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Heebo" rel="stylesheet">
    <!-- link css external -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- link static -->
    <link rel="stylesheet" href ="{%static 'css/index.css'%}" type="text/css">
    {% block head %}
        <!-- head -->
    {% endblock %}
    <title>
        {% block title %}
        <!-- title -->
        {% endblock %}
    </title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- bootstrap csss -->
</head>

<body>
    <nav>
        {% include "navbar.html" %}
    </nav>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% include "footer.html" %}
    </footer>
    <!-- link scripts -->
    {% block script %}
    {% endblock %}
</body>
</html>

templates/navbar.html
{%load static%}
<nav class="navbar navbar-expand-lg navbar-dark dark-blue-bg">
  <a class="navbar-brand" href="{%url 'home:home'%}"><img src="{%static 'media/android-chrome-512x512.png'%}" width="32" height="32" alt="IMTI FTUI"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'home:home'%}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'investiga:investiga'%}">Investiga</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'kastrattv:kastrattv'%}">Kastrat TV</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Berita
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'news:CardEvent'%}">Review Event</a>
          <a class="dropdown-item" href="{%url 'news:POEvent'%}">PO Announcement</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'sopkunjungan:sopkunjungan'%}">SOP</a>
      </li>

    </ul>
  </div>
</nav>